services:
  - type: web
    name: flask-quiz-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    pythonVersion: "3.11.9"
    envVars:
      - key: DATABASE_URL
        value: "postgresql://bars:7AJTm2ZafCE8FdV8GtPWBWHz0CmaDlg8@dpg-d48curjipnbc73de2jh0-a.frankfurt-postgres.render.com/quiz_db_y51y"
      - key: SECRET_KEY
        value: "your-secret-key-here"